---
title: "Simulation"
author: "Sergei Tarasov"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
params:
  output_dir: "/output"
---

# Simulate Data used in this study

```{r, setup, include=FALSE}
library(DT)
library(ggplot2)
library(dplyr)
library(knitr)
library(kableExtra)
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r message=FALSE}

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ installations and dependencies  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source('R/utils/dependencies.R')
#source('R/hiclasse/HiClaSSE-R.R') # pure R implementation of HiCLaSSE
#source('R/hiclasse/HiClaSSE_cpp.R') # fast implementation


```

## Setting-up Q matrices for inference

### CID4

```{r}
# trait
Q_t <- initQ(c(0,1), c(2, 2))
# diversification regime
Q_r2 <- initQ(c('A','B'), c(2,2))
# speciation rates for tracking the order
La4 <- diag(c(-3,-1),2)
La4 = La4 %x% diag(1,2)
# order according to regimes
Q_cid4.r <- amaSMM(Q_r2, Q_t)

# order according to trait
v=c(1,3, 2,4)
Q_cid4.t <- Q_cid4.r[v,v]

print(Q_cid4.r)
print(La4)
print(Q_cid4.t)
print(La4[v,v])


```
## Set up

```{r}
NSIM=1 # N of trees to simulate
max.taxa = 100
```


## Simulate misse 3

```{r}


Q_hisse <- TransMatMakerHiSSE(hidden.traits=2)
Q_t <- initQ(c(0,1), c(0.2,0.2)) # trait
Q_r <- initQ(c('A','B', 'C'), c(0.1)) # diversification regimes
Q_cid <- amaSMM(Q_r, Q_t, diag.as = NA)
Q_cid

v = c(1,3,5,  2, 4, 6)
Q_cid[v,v] # lumpable with respect to trait

# diversification pars
#lam <- c(0.05, 0.05, 0.1, 0.1)
lam <- c(0.1, 0.1, 0.05, 0.05, 0.05, 0.05)
mu <- rep(0.001, 6)
div.pars <- convert2ratesHisse(lam, mu)
div.pars

phy<- list()
i=1
for (i in 1:NSIM){
  simulated.result <- SimulateHisse(div.pars$turnover, div.pars$eps, Q_cid, max.taxa=max.taxa, x0 = sample(0:5, 1), nstart = 2)
  simulated.result
  phy[[i]] <- SimToPhylo(simulated.result$results, include.extinct=FALSE)

}

#phy[[1]]$tip.state
plot(phy[[1]])

which(is.na(phy))
#saveRDS(phy, file='R/data/sim/p-10tr.RDS')
#phy <- readRDS(file='R/data/sim/CID4-1tr.RDS')

```

pattern freq

```{r}
lapply(phy, function(x) length(x$tip.state))
patterns <- lapply(phy, function(x) x$tip.state)
patterns_df <- as.data.frame(do.call(rbind, patterns))

# Count the frequency of each unique pattern
pattern_freq <- as.data.frame(table(apply(patterns_df, 1, paste, collapse = "-")))

```



```{r}
lapply(phy, function(x) x$tip.state)
```



### Simulate CID: 100 tips, 100 trees

```{r eval=FALSE}


max.taxa = 100

Q_cid <- Q_cid4.r/10
# > Q_cid
#      A0   A1   B0   B1
# A0 -0.4  0.2  0.2  0.0
# A1  0.2 -0.4  0.0  0.2
# B0  0.2  0.0 -0.4  0.2
# B1  0.0  0.2  0.2 -0.4
v = c(1,3, 2, 4)
Q_cid[v,v] # lumpable with respect to trait

# diversification pars
lam <- c(0.3, 0.3, 0.1, 0.1)
mu <- rep(0.01, 4)
div.pars <- convert2ratesHisse(lam, mu)
div.pars

phy<- list()
i=1
for (i in 1:NSIM){
  simulated.result <- SimulateHisse(div.pars$turnover, div.pars$eps, Q_cid, max.taxa=max.taxa, x0 = sample(0:3, 1), nstart = 2)
  simulated.result
  phy[[i]] <- SimToPhylo(simulated.result$results, include.extinct=FALSE)
  #phy[[i]]$tip.state

}

#which(is.na(phy))
#saveRDS(phy, file='R/data/sim/phy_CID4-100tips-100tr.RDS')
#phy <- readRDS(file='R/data/sim/phy_CID4-100tips-100tr.RDS')
```

## Read in data

```{r}
NSIM = 10
#phy <- readRDS(file='R/data/sim/phy_CID4-10tr.RDS')
phy <- readRDS(file='R/data/sim/phy_CID4-100tips-100tr.RDS')
phy <- phy[1:10]
```



# Inference

```{r}

tree <- phy[[1]]

trans.rates = TransMatMaker.old(hidden.states=TRUE)
trans.rates.nodual = ParDrop(trans.rates, c(3,5,8,10))
#setting all transition rates equal
trans.rates.nodual.allequal = ParEqual(trans.rates.nodual, c(1,2,1,3,1,4,1,5,1,6,1,7,1,8))
trans.rates.nodual.allequal

turnover.anc = c(1,1,2,2)
eps.anc = c(1,1,2,2)
#--------------------------------
mytree.p <- tree
mydata.p.sse <- dat

#CID-2 Model
turnover.anc = c(1,1,2,2)
eps.anc = c(1,1,2,2)
#full 8 transition model
trans.rates = TransMatMaker.old(hidden.states=TRUE)
trans.rates.nodual = ParDrop(trans.rates, c(3,5,8,10))
#setting all transition rates equal
trans.rates.nodual.allequal = ParEqual(trans.rates.nodual, c(1,2,1,3,1,4,1,5,1,6,1,7,1,8))
trans.rates.nodual.allequal
CID2.p <-  hisse.old(mytree.p, mydata.p.sse, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc, eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal,output.type="raw")

print(CID2.p$loglik)
#-988.3828

#2*5-2*CID2.p$loglik
print(CID2.p$AIC)
# 1986.766
```



