---
title: "Yule-congruence"
author: "Sergei Tarasov"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
params:
  output_dir: "/output"
---

# Yule-congruence


Here, we validate HiClaSSE against available models from diversitree package.

```{r, setup,  include=FALSE}
library(DT)
library(ggplot2)
library(dplyr)
library(knitr)
library(kableExtra)
library(here)
knitr::opts_knit$set(root.dir = here::here(), cache = TRUE)
```

```{r message=FALSE}

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ installations and dependencies  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# source dependencies and install them if they are not
source('R/utils/dependencies.R')
#source('R-models/my-ClaSSE.R') # pure R implementation of HiCLaSSE
source('R/hiclasse/HiClaSSE-R.R') # pure R implementation of HiCLaSSE
source('R/hiclasse/HiClaSSE_cpp.R') # fast implementation


```


## Make data

```{r}
# BiSSE
pars <- c(1.5, 0.5, .1, .1, 1.2, 1)
names(pars) <- diversitree:::default.argnames.bisse()
#pars
phy <- tree.bisse(pars, max.taxa=10, x0=0)
tree <- phy
states <- phy$tip.state
states



```




### BiSSE-ness Likelihood


```{r}

lik.bi <- make.bisse(phy, phy$tip.state)
pars.bi <- 0 * starting.point.bisse(phy)
pars.bi['lambda0'] <- 0.3
pars.bi['lambda1'] <- 0.1
pars.bi['q01'] <- 0.5
pars.bi['q10'] <- 0.6

lik.bi(pars.bi, intermediates=T, root=ROOT.GIVEN, root.p=c(.5, .5))

lik.c <- make.classe(phy, phy$tip.state+1, 2)
pars.c <- 0 * starting.point.classe(phy, 2)
pars.c['lambda111'] <- 0.3
pars.c['lambda222'] <- 0.3
pars.c['q12'] <- 0.5
pars.c['q21'] <- 0.5

lik.c(pars.c, intermediates=F, root=ROOT.GIVEN, root.p=c(.5, .5))

pars.c2 <- 0 * starting.point.classe(phy, 2)
#pars.c2['lambda111'] <- 0.3/2
pars.c2['lambda122'] <- 0.3
pars.c2['lambda222'] <- 0.3
#pars.c2['lambda212'] <- 0.1/2
pars.c2['q12'] <- 0.5
pars.c2['q21'] <- 0.5

l1 <- lik.c(pars.c, intermediates=F, root=ROOT.GIVEN, root.p=c(.5, .5))
l2 <- lik.c(pars.c2, intermediates=F, root=ROOT.GIVEN, root.p=c(.5, .5))

l1
l2
attr(l1,"intermediates")$init-attr(l2,"intermediates")$init

##  BiSSEness:
lambda0 = 0.3
p0c = 0
p0a = 0
lambda1 = 0.3
p1c = 0
p1a = 0

# lambda0, lambda1,  mu0, mu1,  q01, q10,   p0c, p0a, p1c, p1a
pars.bi <-c(lambda0, lambda1,  0, 0,  .5, .5, p0c, p0a,   p1c, p1a)
#pars.bi
lik.bisseness <- make.bisseness(tree, states)
bisseness <- lik.bisseness(pars.bi, intermediates=F, root=ROOT.GIVEN, root.p=c(.5, .5))
bisseness

##  BiSSEness:
lambda0 = 0.3
p0c = 1
p0a = 1
lambda1 = 0.3
p1c = 0
p1a = 0

# lambda0, lambda1,  mu0, mu1,  q01, q10,   p0c, p0a, p1c, p1a
pars.bi <-c(lambda0, lambda1,  0, 0,  .5, .5, p0c, p0a,   p1c, p1a)
#pars.bi
lik.bisseness <- make.bisseness(tree, states)
bisseness <- lik.bisseness(pars.bi, intermediates=F, root=ROOT.GIVEN, root.p=c(.5, .5))
bisseness
```


```{r}
tree
tree$edge.length[18]
tree$edge.length[17]
plot(tree)
nodelabels()
edgelabels()
```



```{r}

# this is character coding at tips. It sets MiSSE model
Args <- list(
  Nstates = 2L,
  y = list(
    c(0,0, 1,0),
    c(0,0, 0,1)
  ))

newArgs <- makeArgs(Args)
printArgsGlobal()
args <- argnames_HiClaSSE(2)
#args
args$pars
#length(args$pars)

#Q3

pars.hc <- rep(0, length(args$pars))
names(pars.hc) <- args$pars
pars.hc['lam000'] <- 0.5
pars.hc['lam111'] <- 0.5
pars.hc['mu0'] <-pars.hc['mu1'] <-0
pars.hc['q01'] <- .5
pars.hc['q10'] <- .5

pars.hc
pars_to_arrays(pars.hc, 2)


root <- c(1/2, 1/2)
lik.c <- make.HiClasse_cpp(tree, states,  sampling.f=NULL,  strict=TRUE, control=list(backend = "gslode"), newArgs)
#states.new <- sample(c(0,1), 10, replace = T)
#names(states.new) <- names(states)
#lik.c <- make.HiClasse_cpp(tree, states.new,  sampling.f=NULL,  strict=TRUE, control=list(backend = "gslode"), newArgs)
lik.hc1 <- lik.c(pars.hc, intermediates=F, root=ROOT.GIVEN, root.p=root, condition.surv=T)
lik.hc1

pars.hc2 <- rep(0, length(args$pars))
names(pars.hc2) <- args$pars
#pars.hc2['lam000'] <- 0.3
pars.hc2['lam011'] <- 0.5
pars.hc2['lam111'] <- 0.5
pars.hc2['mu0'] <-pars.hc['mu1'] <-0
pars.hc2['q01'] <- .5
pars.hc2['q10'] <- .5

pars.hc2
pars_to_arrays(pars.hc2, 2)

lik.hc2 <- lik.c(pars.hc2, intermediates=F, root=ROOT.GIVEN, root.p=root, condition.surv=T)

lik.hc1
lik.hc2
lik.hc1-lik.hc2


```
```{r}
t=tree$edge.length[18]
init=cbind(c(0,0,1,1), c(0,0,1,1))
initial.conditions.HiClasse_cpp(init, pars.hc2, t)

y1=c(0,0,1,1)
tt <- seq(0, tree$edge.length[18], length=1001)
d=lsoda(y1, tt, derivs.HiClasse_cpp_List, pars.hc) %>% tail(., 1)
library(expm)
Q_t <- initQ(c(0,1), c(.1, .1)) 
d = c(d[2:5])
d/sum(d)
log(d)+log(sum(d))
d-log(sum(d))
log(d)+log(d[3]+ d[4])

attr(lik.hc2,"intermediates")$lq[13]
d*d
c(d[2:5])
initial.conditions.HiClasse_cpp(cbind(d,d), pars.hc2, 2)

l1=attr(lik.hc2,"intermediates")$base[,9]
initial.conditions.HiClasse_cpp(cbind(l1,l1), pars.hc2, 2)

l1[3]^2*0.3
l1[4]^2*0.3
```

