---
title: "Simulation"
author: "Sergei Tarasov"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
params:
  output_dir: "/output"
---

# Simulate Data

```{r, setup, include=FALSE}
library(DT)
library(ggplot2)
library(dplyr)
library(knitr)
library(kableExtra)
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r message=FALSE}

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##  ~ installations and dependencies  ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source('R/utils/dependencies.R')
source('R/hiclasse/HiClaSSE-R.R') # pure R implementation of HiCLaSSE
source('R/hiclasse/HiClaSSE_cpp.R') # fast implementation


```

## Setting-up Q matrices for inference

### CID4

```{r}
# trait
Q_t <- initQ(c(0,1), c(2, 2))
# diversification regime
Q_r2 <- initQ(c('A','B'), c(2,2))
# speciation rates for tracking the order
La4 <- diag(c(-3,-1),2)
La4 = La4 %x% diag(1,2)
# order according to regimes
Q_cid4.r <- amaSMM(Q_r2, Q_t)

# order according to trait
v=c(1,3, 2,4)
Q_cid4.t <- Q_cid4.r[v,v]

print(Q_cid4.r)
print(La4)
print(Q_cid4.t)
print(La4[v,v])


```

## Simulate: 100 tips, 10 trees

```{r}


NSIM=10 # N of trees to simulate
max.taxa = 100

Q_hisse <- TransMatMakerHiSSE(hidden.traits=1)
Q_t <- initQ(c(0,1), c(0.05,0.2)) # trait
Q_r <- initQ(c('A','B'), c(0.2,0.05)) # diversification regimes
Q_cid <- amaSMM(Q_r, Q_t, diag.as = NA)
Q_cid
# > Q_cid # same state order as in Q_hisse
#      A0   A1  B0   B1
# A0   NA 0.05 0.2 0.00
# A1 0.20   NA 0.0 0.20
# B0 0.05 0.00  NA 0.05
# B1 0.00 0.05 0.2   NA
v = c(1,3, 2, 4)
Q_cid[v,v] # lumpable with respect to trait

# diversification pars
#lam <- c(0.05, 0.05, 0.1, 0.1)
lam <- c(0.1, 0.1, 0.05, 0.05)
mu <- rep(0, 4)
div.pars <- convert2ratesHisse(lam, mu)
div.pars

phy<- list()
i=1
for (i in 1:NSIM){
  simulated.result <- SimulateHisse(div.pars$turnover, div.pars$eps, Q_cid, max.taxa=max.taxa, x0 = sample(0:3, 1), nstart = 2)
  simulated.result
  phy[[i]] <- SimToPhylo(simulated.result$results, include.extinct=FALSE)

}

#saveRDS(phy, file='R/data/phy_CID4.RDS')
phy <- readRDS(file='R/data/phy_CID4.RDS')

```

## ------
## Simulation Settings

```{r}

NSIM= 100 # N of trees to simulate

```


## Simulate: 100 tips, 100 trees

```{r}


max.taxa = 100

Q_cid <- Q_cid4.r/10
# > Q_cid
#      A0   A1   B0   B1
# A0 -0.4  0.2  0.2  0.0
# A1  0.2 -0.4  0.0  0.2
# B0  0.2  0.0 -0.4  0.2
# B1  0.0  0.2  0.2 -0.4
v = c(1,3, 2, 4)
Q_cid[v,v] # lumpable with respect to trait

# diversification pars
lam <- c(0.3, 0.3, 0.1, 0.1)
mu <- rep(0.01, 4)
div.pars <- convert2ratesHisse(lam, mu)
div.pars

phy<- list()
i=1
for (i in 1:NSIM){
  simulated.result <- SimulateHisse(div.pars$turnover, div.pars$eps, Q_cid, max.taxa=max.taxa, x0 = sample(0:3, 1), nstart = 2)
  simulated.result
  phy[[i]] <- SimToPhylo(simulated.result$results, include.extinct=FALSE)

}

saveRDS(phy, file='R/data/phy_CID4-100tips-100tr.RDS')
```


## Simulate: 500 tips, 100 trees

```{r}
max.taxa = 500

Q_cid <- Q_cid4.r/10
# > Q_cid
#      A0   A1   B0   B1
# A0 -0.4  0.2  0.2  0.0
# A1  0.2 -0.4  0.0  0.2
# B0  0.2  0.0 -0.4  0.2
# B1  0.0  0.2  0.2 -0.4
v = c(1,3, 2, 4)
Q_cid[v,v] # lumpable with respect to trait

# diversification pars
lam <- c(0.3, 0.3, 0.1, 0.1)
mu <- rep(0.01, 4)
div.pars <- convert2ratesHisse(lam, mu)
div.pars

phy<- list()
i=1
for (i in 1:NSIM){
  simulated.result <- SimulateHisse(div.pars$turnover, div.pars$eps, Q_cid, max.taxa=max.taxa, x0 = sample(0:3, 1), nstart = 2)
  #simulated.result
  phy[[i]] <- SimToPhylo(simulated.result$results, include.extinct=FALSE)
}

#which(is.na(phy))
saveRDS(phy, file='R/data/phy_CID4-500tips-100tr.RDS')
```


## Simulate: 1000 tips, 100 trees

```{r}
max.taxa = 1000

Q_cid <- Q_cid4.r/10
# > Q_cid
#      A0   A1   B0   B1
# A0 -0.4  0.2  0.2  0.0
# A1  0.2 -0.4  0.0  0.2
# B0  0.2  0.0 -0.4  0.2
# B1  0.0  0.2  0.2 -0.4
v = c(1,3, 2, 4)
Q_cid[v,v] # lumpable with respect to trait

# diversification pars
lam <- c(0.3, 0.3, 0.1, 0.1)
mu <- rep(0.01, 4)
div.pars <- convert2ratesHisse(lam, mu)
div.pars

phy<- list()
i=1
for (i in 1:NSIM){
  simulated.result <- SimulateHisse(div.pars$turnover, div.pars$eps, Q_cid, max.taxa=max.taxa, x0 = sample(0:3, 1), nstart = 2)
  simulated.result
  phy[[i]] <- SimToPhylo(simulated.result$results, include.extinct=FALSE)

}

saveRDS(phy, file='R/data/phy_CID4-1000tips-100tr.RDS')
```




